### ISSUE TITLE
Information on the rewrite

### ISSUE THREAD

**Issue by tiredenzo** [wvanbergen/adyen#106]
Hello there !

Can we have a non exhaustive explanation of the rewrite that is currently happening ? :)

Thanks a lot

**Comment by wvanbergen** [comment]
- The old implementation was using string concatenation to assemble XML requests. This became more complicated as we added support for more and more optional fields. The new implementation uses simple POST parameters, which you can easily remove or add to a request. This also cuts down the amount of code significantly.
- The old implementation's API was not extensible. Adding new features without breaking backwards compatibility was basically impossible, or made features way more complicated to add. The new implementation uses option hashes with named key values, which makes it trivial to add support for extra, optional fields.

So this is happening so I can continue to maintain this library in my free time. At the same time, I have taken the opportunity to fix some other things, like support for client-side encryption and integration tests.

**Comment by rngtng** [comment]
great stuff! Thanks for your continuous efforts - and happy new year!

**Comment by tiredenzo** [comment]
Ok thanks a lot :)
