### ISSUE TITLE
3DS over SOAP

### ISSUE THREAD

**Issue by tiredenzo** [wvanbergen/adyen#107]
Hello I could use a little advice :)

I first implemented REST API interfaces but just switched to the SOAP as recurring payments are apparently not in the REST interface.

But when doing 3ds implementation, I don't see any redirect_shopper? or issuer_url or pa_request or md related code in Adyen::API::PaymentService::AuthorisationResponse.

Is this feature unavailable through this interface ?

Should i do a pull request even if you are recoding this lib ? otherwise I would just monkey patch it

SOAP Interface seems to be more advanced than REST interface.
So if there is a pull request to do... Should I concentrate on making SOAP more evolved or REST ??

Thanks

**Comment by wvanbergen** [comment]
SOAP is deprecated, so I will not accept any PRs anymore. REST already supports 3D secure. See the example server, which already implements the 3D secure flow using the REST API. 

While it is true that the SOAP implementation has more methods defined, the REST implementation is more versatile, and can support any API call with any parameter by using the generic `Adyen::REST::Request` and `Adyen::REST::Response` objects.

**Comment by tiredenzo** [comment]
Ok so should I do a PR for recurring payment in REST ?

**Comment by tiredenzo** [comment]
Ok so should I do a PR for recurring payment in REST ?
I'll look a bit more deeply into REST so :)
I have tom implement recurring @ first and IDEAL later on :)

**Comment by wvanbergen** [comment]
Yes, pull requests would be great!

E.g., see https://github.com/wvanbergen/adyen/blob/master/lib/adyen/rest/authorise_payment.rb and https://github.com/wvanbergen/adyen/blob/master/lib/adyen/rest/modify_payment.rb for examples on how to implement API calls as methods.

IIRC, recurring payments require some additional parameters to the standard authorize call. I am not too sure about iDeal. Can you do that via the API or does it require using the hosted paged?

**Comment by tiredenzo** [comment]
Hello, I have done a first implementation but before doing a pull request and writing up the tests...
I would really appreciate if we can discuss on the type of implementation that i have done:

Let me explain i have cleated ````Adyen::REST::AuthoriseRecurringPayment::Request```` and ````Adyen::REST::ReauthoriseRecurringPayment::Request```` in order to force some ````@required_attributes```` to be present upon the use of this requests they are accessible. Those classes inherit from  ````Adyen::REST::AuthorisePayment::Request````
by calling ````Adyen::REST.client.authorise_recurring_payment_request```` and ````Adyen::REST.client.authorise_recurring_payment_request````

I am not really sure you'll like the way i have done things so I prefer to discuss things before i go further with your recommandations.

Here is the code

````
module Adyen
  module REST

    module AuthoriseRecurringPayment
      class Request < Adyen::REST::AuthorisePayment::Request
        def initialize(action, attributes, options)
          attributes[:recurring] ||= { contract: 'RECURRING' }
          super(action, attributes, options)
          @required_attributes += ['paymentRequest.shopperEmail',
            'paymentRequest.recurring.contract',
            'paymentRequest.shopperReference',
          ]
        end
      end
    end

    module ReauthoriseRecurringPayment
      class Request < Adyen::REST::AuthorisePayment::Request
        def initialize(action, attributes, options)
          attributes[:recurring] ||= { contract: 'RECURRING' }
          attributes[:shopper_interaction] ||= 'ContAuth'
          attributes[:selected_recurring_detail_reference] ||= 'LATEST'
          super(action, attributes, options)
          @required_attributes += ['paymentRequest.shopperEmail',
            'paymentRequest.shopperReference',
            'paymentRequest.recurring.contract',
            'paymentRequest.shopperInteraction'
          ]
        end
      end
    end

    module AuthorisePayment

      def authorise_recurring_payment_request(attributes={})
        Adyen::REST::AuthoriseRecurringPayment::Request.new('Payment.authorise', attributes,
          prefix: 'payment_request',
          response_class: Adyen::REST::AuthorisePayment::Response,
          response_options: { prefix: 'payment_result' })
      end

      def authorise_recurring_payment
        request = authorise_recurring_request(attributes)
        execute_request(request)
      end

      alias_method :authorize_recurring_payment_request, :authorise_recurring_payment_request
      alias_method :authorize_recurring_payment, :authorise_recurring_payment


      def reauthorise_recurring_payment_request(attributes={})
        Adyen::REST::ReauthoriseRecurringPayment::Request.new('Payment.authorise', attributes,
          prefix: 'payment_request',
          response_class: Adyen::REST::AuthorisePayment::Response,
          response_options: { prefix: 'payment_result' })
      end

      def reauthorise_recurring_payment
        request = reauthorise_recurring_request(attributes)
        execute_request(request)
      end

      alias_method :reauthorize_recurring_payment_request, :reauthorise_recurring_payment_request
      alias_method :reauthorize_recurring_payment, :reauthorise_recurring_payment

    end
  end
end
````

Thank you for your time Willem

**Comment by wvanbergen** [comment]
I'm not too sure yet about organizing code for the API. I'm not a big of the the two modules with the subclasses. Not sure how exactly I would change it though.

I'll accept a PR in this current form, if you add unit and functional tests to it. Thanks for doing this! :+1:

**Comment by tiredenzo** [comment]
Ok Im not big fan of the two modules either... but iI really don't know how I would change it either, Thanks

**Comment by wvanbergen** [comment]
Let's get it included first, I may refactor it a bit if I have better ideas.
