### ISSUE TITLE
Which version the Adyen API is the gem using?

### ISSUE THREAD

**Issue by dlbock** [wvanbergen/adyen#116]
Hi @wvanbergen, Adyen's online manuals refer to `https://pal-%s.adyen.com/pal/servlet/Recurring/V12`, but the code in https://github.com/wvanbergen/adyen/blob/v1.6.0/lib/adyen/api/recurring_service.rb#L22 uses `https://pal-%s.adyen.com/pal/servlet/soap/Recurring`, but it's not clear which version of the API it's using?

Just for some context, we've currently forked the 1.6.0 version of this gem because we needed to add support for billing address (AVS) data when submitting a payment authorisation request, and since v1.6.0 is being deprecated and we're not yet equipped to upgrade to ruby 2.x.

Thanks!
-dahlia

**Comment by wvanbergen** [comment]
I don't know - when I initially created the gem, the endpoint URL didn't include a version yet. 

There have been many features added to the gem that were not available in the API when I started the project, and that seems to work. So I assume it uses the latest API version if you don't specify a number?

**Comment by dlbock** [comment]
`https://pal-%s.adyen.com/pal/servlet/Recurring` actually reverts back to V1, but the endpoint that the gem uses has an extra `/soap/` --> `https://pal-%s.adyen.com/pal/servlet/soap/Recurring`

**Comment by wvanbergen** [comment]
I am not sure - I just copy pasted whatever was in the manual at the time, but I don't know anymore what version it was.

**Comment by dlbock** [comment]
Okay, cool. Thanks!
