### ISSUE TITLE
Notifications processing not implemented

### ISSUE THREAD

**Issue by knleva** [wvanbergen/adyen#120]
Hello,

Am I missing something obvious or does the proposed version of the log method completely ignore the structure of the Notifications sent by Adyen? Here is what one looks like:

{"live"=>"true",
  "notificationItems"=>
   [{"NotificationRequestItem"=>
      {"amount"=>{"currency"=>"EUR", "value"=>1100},
       "eventCode"=>"PENDING",
		"eventDate"=>"00",
       "merchantAccountCode"=>"AccountCode",
       "merchantReference"=>"testMerchantRef1",
       "paymentMethod"=>"paypal",
       "pspReference"=>"8313842560770001",
       "success"=>"true"}}],
  "controller"=>"adyen",
  "action"=>"notify",
  "adyen"=>
   {"live"=>"true",
    "notificationItems"=>
     [{"NotificationRequestItem"=>
        {"amount"=>{"currency"=>"EUR", "value"=>1100},
         "eventCode"=>"PENDING",
		"eventDate"=>"00",
         "merchantAccountCode"=>"AccountCode",
         "merchantReference"=>"testMerchantRef1",
         "paymentMethod"=>"paypal",
         "pspReference"=>"8313842560770001",
         "success"=>"true"}}]}}

Yet, the log method suggested on the wiki assume flat structure (key/value) pairs within "params":
    self.new.tap do |notification|
      params.each do |key, value|
        setter = "#{key.to_s.underscore}="
        notification.send(setter, value) if notification.respond_to?(setter)
      end
      notification.save!
    end

I also see this routine mentioned in the documentation here - Adyen::Notification::HttpPost.log(request), but it's not to be found anywhere in the source code of the gem. I am assuming that HttpPost.log is what used to convert the Adyen messages to the flat format required to be correctly saved into the model?

Thanks in advance for clarification.
Lev

**Comment by wvanbergen** [comment]
Handling notifications is not part of this gem (yet). The only thing we currently have is a model generator to store to notifications in the DB.

A good notification handler:
- Stores the notification parameters somewhere
- Is idempotent. So, set a good primary key on the table to prevent duplicates from being inserted. The model generator should generate a proper primary key
- For-non duplicate events, triggers business logic in your app.

I am welcoming additions to this gem that would make doing this easier in Rack/Rails apps.

**Comment by knleva** [comment]
Hi Willem, thanks for your response. My question was actually about storing the notifications, but I have resolved the issue since I figured out why it wasn't working. I had to change the setting on Adyen control panel to send HTTP POST requests instead of JSON that was set by default. Lev

**Comment by rngtng** [comment]
btw. speaking of Notifications, let Adyen know you want to have *all* the data. By default they were sending us just basic info, and it took us a while to get hold on the full set, like raw acquirer response code, etc.
