### ISSUE TITLE
Bad IP transmitted to adyen when used behind reverse proxy

### ISSUE THREAD

**Issue by tiredenzo** [wvanbergen/adyen#124]
Hello shouldn't we use
``request.remote_ip``
instead of
``request.ip``

https://github.com/wvanbergen/adyen/blob/056f40689eec4ffd114c0881701c75dcad4e34d9/lib/adyen/rest/authorise_payment.rb#L27

as remote_ip gets the good value behind a reverse proxy. Should i do a PR for that ?

**Comment by wvanbergen** [comment]
:+1:, a PR for this is welcome.

**Comment by wvanbergen** [comment]
Closing this.

The request integration is based on Rack. `Rack::Request` doesn't have a `remote_ip` method, that only exists in Rails.

`Rack::Request` will properly take `X-Forwarded-For` headers into account when determining the ip address:

- In version 2.0: https://github.com/rack/rack/blob/master/lib/rack/request.rb#L256-L265
- In version 1.6: https://github.com/rack/rack/blob/1-6-stable/lib/rack/request.rb#L348-L357
- In version 1.5: https://github.com/rack/rack/blob/1-5-stable/lib/rack/request.rb#L348-L363 (although the logic is slightly different).

So: make sure you configure your reverse proxies to properly set `X-Forwarded-For` headers, and it should work.
