### ISSUE TITLE
Recurring payment flow does not work

### ISSUE THREAD

**Issue by Overbryd** [wvanbergen/adyen#129]
Hi,

I am using your `Adyen::API` implementation to build a recurring payment flow.
It consists out of the following steps:

1. Authorise a payment for a recurring contract (no charge should happen)

2. Maybe capture the funds later on if needed (a charge should happen, without the users interaction)

I am using the top level API of your Ruby library, according to the Adyen documentation:

1. `Adyen::API.authorise_payment(reference, { currency: "EUR", value: 100 }, {}, { encrypted: { json: "..." } }, true)` with the correct amount set, the option `recurring_contract` is set to `true`.

2. `Adyen::API.capture_payment(psp_reference, { currency: "EUR", value: 100 })` with the correct amount. The `psp_reference` was acquired from the previous response.

Unfortunately this does not work, and results in an error:

`validation 100 No amount specified`

Could you please elaborate why the Ruby API does not work as advertised?
I am also happy to help if you are short on time regarding a fix, but first I need to know wether it is used correctly.

Best, Lukas Rieder

**Comment by wvanbergen** [comment]
`Adyen::API` is deprecated and unmaintained. 

Try upgrading to `Adyen::REST` which is available in the latest beta release. If that one doesn't work, getting your help improving it would be very welcome. I am not using this gem myself anymore, and my time to work on it is limited.

**Comment by Overbryd** [comment]
Ok thanks for the response. I also figured out, with the Adyen support team, that some of the endpoints this gem is using are from their previous server version. They are still usable, but the support team advises using the "newer" endpoints.

> The endpoint /pal/adapter/httppost corresponds to our previous version and you can still use it.
The endpoints provided in our online documentations correspond to our newer endpoints.
Both endpoints are working and you can access to the same functionalities for standard accesses (payment , recurring, etc) but it would be better to use the new ones.

Given this, I went forth and created a [new API wrapper `adyen_client`](https://github.com/Overbryd/adyen_client) based on the new API version, geared towards using API + CSE.
