### ISSUE TITLE
Adyen REST API endpoints different from gem

### ISSUE THREAD

**Issue by jonathanpa** [wvanbergen/adyen#130]
I am working to add the Payout to the gem and when I read the API documentation at https://docs.adyen.com/manuals/api-manual/api-endpoints, I see that the endpoints are https://pal-test.adyen.com/pal/servlet/Payment/v12/<action> and it's different from what is in https://github.com/wvanbergen/adyen/blob/master/lib/adyen/rest/client.rb#L107
`ENDPOINT = 'https://pal-%s.adyen.com/pal/adapter/httppost'`

So some things are a little unclear for me:
* A call to `https://pal-%s.adyen.com/pal/adapter/httppost` with `action='Payment.authorise'` is equivalent to call `https://pal-test.adyen.com/pal/servlet/Payment/v12/authorise` ?
* Do you know if with `adapter/httppost` you are calling the version 12 (*v12*) of the Adyen API ?
* I understand the code using `prefix` in `Rest::Request` but don't find why to use it in the Adyen API documentation (the JSON examples don't show usage of prefix).

Thanks

**Comment by wvanbergen** [comment]
Looks like this will be solved by #148. Closing this. cc @alexGaspar
