### ISSUE TITLE
HPP resURL parameter support

### ISSUE THREAD

**Issue by unabl4** [wvanbergen/adyen#131]
Not a particularly severe issue, but to what I understand the gem does not support 'resURL' parameter that can be passed to HPP overriding a default 'resURL' set in a skin.

Should I consider making a pull request?
AFAIK, it's only a matter of adjusting the 'CAMELCASE_EXCEPTIONS' in util.rb

**Comment by wvanbergen** [comment]
Yeah, a PR for this is welcome!

**Comment by wvanbergen** [comment]
Closing this as stale.

If you are still interested in this, feel free to open a pull request, and make sure it works with the new `Adyen::HPP` stuff that was released recently.
