### ISSUE TITLE
Travis broken on build

### ISSUE THREAD

**Issue by lucasgomide** [wvanbergen/adyen#137]
When travis build the application at jruby 1.7.19, it's break.
`Gem::InstallError: mime-types-data requires Ruby version >= 2.0.`

I did some attempts to solve it.. but nothing work. 

Any Ideas ?

**Comment by lucasgomide** [comment]
I'v solved adding as dependency `s.add_development_dependency('mime-types', '~> 2')` 

Look for the PR #138

**Comment by mvz** [comment]
This was fixed in #143.
