### ISSUE TITLE
Latest release still signs with deprecated SHA-1, support will end in July

### ISSUE THREAD

**Issue by awendt** [wvanbergen/adyen#140]
Latest released version is 2.0.0pre2 from March 2015. That version still uses SHA-1 for the merchant signature. Adyen has announced (emphasis mine):

> SHA-1 is no longer a recommended hashing algorithm from the PCI Security Standards Council.
> Therefore, you must upgrade your integration to HMAC signature using SHA-256 hashing
> algorithm by **1 July 2016.**

It'd be nice to have a release (even a pre-release one) that includes SHA-256 for the merchant signature, as merged in #119.

**Comment by wvanbergen** [comment]
Released latest master as 2.0.0 (final)
