### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by morgoth** [wvanbergen/adyen#141]
Are you planning to add JSON API integration?
From Adyen docs, this is a preferred way of communicating:

```
 JSON should be the default way to integrate to Adyen unless there is a strong preference to use another data representation
```

**Comment by wvanbergen** [comment]
- `Adyen::REST` is using HTTP from-encoding. I have no problem changing this to JSON, but it's unlikely I will work on this myself anytime soon. Pull requests are welcome.
- `Adyen::API` is deprecated, and uses SOAP/XML. Don't use this anymore.
