### ISSUE TITLE
Complete migration to Minitest

### ISSUE THREAD

**Issue by mvz** [wvanbergen/adyen#151]
This gem currently uses both minitest and rspec to test. I'd like to combine all tests to use only one or the other. @wvanbergen I can see that you started moving all tests to minitest a long time ago. Is this still what you want?

**Comment by wvanbergen** [comment]
Yes - I just ran out of steam doing this for the deprecated APIs. Eventually I want to get rid of RSpec, either by rewriting the specs to tests, or just dropping the deprecated functionality eventually.
