### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by lsdr** [wvanbergen/adyen#154]
I'm currently integrating my product with Adyen and planning on using the REST API. Does this still apply?

> Note: this library is corrently undergoing a major rewrite. Information in this README is about the still unreleased version of this library. If you want information about the last released version, check out version 1.6.0.

Or is it OK to use the latest (at this time, 2.2.0) released version?

**Comment by wvanbergen** [comment]
This remark is old (when the latest release was still 1.x). 2.2 is definitely fine for production use. I will remove the remark from the README.
