### ISSUE TITLE
Please support merchant-specific endpoints

### ISSUE THREAD

**Issue by awendt** [wvanbergen/adyen#158]
As per [Adyen's docs](https://docs.adyen.com/developers/api-manual):

> Although generic URL endpoints for our APIs are still supported (API endpoints, Recurring API endpoints), we recommend setting up merchant-specific endpoints. This is the default endpoint configuration option for new merchants.

Right now, there's no way to configure the endpoint using `Adyen.configuration`. It would be nice to have that.

**Comment by wvanbergen** [comment]
I'll happily accept patches to support this, but I am unlikely to work on this myself any time soon. If you want to work on this and need to hand to get started, let me know.

**Comment by awendt** [comment]
@wvanbergen Thanks for the quick feedback!

**Comment by mvz** [comment]
Fixed in #172.
