### ISSUE TITLE
merchantSig not working

### ISSUE THREAD

**Issue by Loschcode** [wvanbergen/adyen#165]
I tried to use this gem for its HPP system but Adyen server didn't accept the merchant signature. I simulated the exact same fields and value with the Check HMAC from Adyen site and it outputs a valid calculated merchant signature from there.

It looks like `LND3LlxV1x/+Lal4pwKnkAyDqdvtzViCequ0Nl1O1kg=` but using the same data, your gem output `fxjZwi/R4xkUaj33JUYj6jcnmyQ=` which doesn't look even remotely the same. Something must be wrong, and when trying to send the form Adyen says the merchant signature is not valid.

I checked the code where you generate the signature itself and it looks fine so I'm wondering why this is happening.

In the project:

```
  Adyen::Form.hidden_fields(
  :currency_code => 'EUR',
  :ship_before_date =>  "2016-12-20", # Date.today,
  :session_validity => "2016-12-20T13:26:43Z", # Time.now,
  :merchant_reference => 'SKINTEST-1482235768306',
  :merchant_account => 'DigpandaCN',
  :skin_code => ENV['adyen_skin'],
  :shared_secret => ENV['adyen_hmac'],
  :payment_amount => 30 * 100 # cents
  )
```
Merchant Signature is `fxjZwi/R4xkUaj33JUYj6jcnmyQ=`

And on the Test HMAC Calculation: 

https://www.dropbox.com/s/cnczs9ojdfkvr57/Screenshot%202016-12-20%2014.22.14.png?dl=0

Merchant Signature is `LND3LlxV1x/+Lal4pwKnkAyDqdvtzViCequ0Nl1O1kg=`

Am I doing something wrong here ? Or there's actually a bug in the calculation ?

**Comment by Loschcode** [comment]
I had to setup the skin with SHA-1 and it resolved the problem. Note that I had to fill in the shared secret myself. Thanks for this lib ;)

**Comment by dhenze** [comment]
@Loschcode can you describe what you mean by "I had to setup the skin with SHA-1"? Running into the same issue and could not find an option to do so yet.
