### ISSUE TITLE
Memory bloat in `Adyen::API.list_recurring_details`

### ISSUE THREAD

**Issue by reneweteling** [wvanbergen/adyen#167]
Hey guys, 

Im afraid im experiencing a memory bloat in the list_recurring_details api call, when we loop through our client base (4K users) we start off with a footprint of 250MB and end up in the 580MB area.

When i remove this line `Adyen::API.list_recurring_details(artist.id)` from my function the memory footprint only increases with 0.5 mb. And with about 280MB.

![image](https://cloud.githubusercontent.com/assets/3830933/22240857/1e0407ee-e21d-11e6-96d6-41f85897e805.png)
![image](https://cloud.githubusercontent.com/assets/3830933/22240944/8eacdcfa-e21d-11e6-9f40-d515384503cc.png)

Thanks guys!

**Comment by reneweteling** [comment]
Small update / work around:

```ruby
Artist.limit(100).each_with_index do |artist, i|
      Adyen::API.list_recurring_details(artist.id)
      GC.start if i % 10 == 0)
end
```

This reduces my batch increase for 100 artists from 67 mb to 2

**Comment by awendt** [comment]
Ouch 🤕 

It would be great to put some effort into this area anyway: `Adyen::API` is deprecated but we don't have support for recurring details in the REST client, as far as I can see.
