### ISSUE TITLE
Validating not mandatory attribute in Payment Request

### ISSUE THREAD

**Issue by LikitSaeLee** [wvanbergen/adyen#175]
Hi, I've looked into the Adyen documentation and it seems that the `shopperEmail` is not a mandatory attribute for the payment request. However, in `Adyen::Rest` we're validating the presence of the `shopperEmail`.

Is there any particular reason to validate the `shopperEmail`? You can find the documentation here: https://docs.adyen.com/developers/api-reference/payments-api#paymentrequest

Thanks

**Comment by wvanbergen** [comment]
Pretty sure this to be required in the past. If this is no longer the case, I will happily accept a PR that removes the validation
