### ISSUE TITLE
gems/adyen-2.3.0/lib/adyen/hpp/request.rb:12: unknown type of %string (SyntaxError)

### ISSUE THREAD

**Issue by jawosis** [wvanbergen/adyen#177]
Hi,

using rails 3.2 and ruby 1.9.3, I get the following errors after installing the adyen gem as described in this wiki (add gem to Gemfile & bundle install):

> /usr/local/rvm/gems/ruby-1.9.3-p551/gems/adyen-2.3.0/lib/adyen/hpp.rb:2:in `require': /usr/local/rvm/gems/ruby-1.9.3-p551/gems/adyen-2.3.0/lib/adyen/hpp/request.rb:12: unknown type of %string (SyntaxError)
> ...     MANDATORY_ATTRIBUTES = %i(currency_code payment_amount ...
> ...                               ^
> /usr/local/rvm/gems/ruby-1.9.3-p551/gems/adyen-2.3.0/lib/adyen/hpp/request.rb:12: syntax error, unexpected $end
> ...     MANDATORY_ATTRIBUTES = %i(currency_code payment_amount ...

Am I missing some installation step?

**Comment by wvanbergen** [comment]
Ruby 1.93 is no longer supported. Specifically, it doesn't support `%i()`. You should upgrade to a more recent version.
