### ISSUE TITLE
Shared secret and test skin

### ISSUE THREAD

**Issue by munhoh94** [wvanbergen/adyen#184]
Hey, I'm learning to incorporate adyen in my rails app and I came across this line of code:

> :shared_secret => SHARED_SECRETS[TEST_SKIN], #HMAC Key for test/production (be careful, it takes time to propagate this key)

I've generated my shared secret key (which is my hmac key) and i have my TEST_SKIN(which is my 8 digit skin code). For :shared_secret, I use my hmac keys directly and there was an invalid request. I noticed from the code its SHARED_SECRETS[TEST_SKIN]. Does this mean that I add the test skin key in an array at the end of the shared secrets?

**Comment by wvanbergen** [comment]
- You need to register your skin using `register_form_skin`: e.g. https://github.com/wvanbergen/adyen/blob/master/test/unit/form_test.rb#L10. 
- Then, you can refer to the identifier you picked for your skin when building forms: e.g. https://github.com/wvanbergen/adyen/blob/master/test/unit/form_test.rb#L19

References to `TEST_SKIN` and `:testing` in this code base relate to the skin in the test account that this library uses to run functional and integration tests against.
