### ISSUE TITLE
psp_reference is not an integer

### ISSUE THREAD

**Issue by x4d3** [wvanbergen/adyen#189]
Hello,

We seems to be having issue with Adyen Test environment which does not seems to be returning integer for `psp_reference` anymore. ("852558434891412B")
This is causing an error in:
https://github.com/wvanbergen/adyen/blob/6865a1d5b73cc14e28c83dd0003a703a0ba79f15/lib/adyen/rest/response.rb#L41
with `ArgumentError · invalid value for Integer()`

**Comment by x4d3** [comment]
The change is actually documented by Adyen: https://support.adyen.com/hc/en-us/articles/360002783080-How-to-check-if-my-integration-supports-alphanumeric-string-references-

**Comment by wvanbergen** [comment]
:+1: This makes sense to change. Can you provide a PR for this? I am currently not actively working on this library, but will happily accept a PR to fix this issue.

**Comment by x4d3** [comment]
Will do.

**Comment by x4d3** [comment]
@wvanbergen this is my attempt: #190
