### ISSUE TITLE
Deprecate in favor of official Adyen Ruby Library

### ISSUE THREAD

**Issue by deepu105** [wvanbergen/adyen#192]
Hello @wvanbergen and contributors

First of all, we would like to thank you for building and maintaining this library. This has served the Adyen community quite well. We do have an [official Ruby library](https://github.com/Adyen/adyen-ruby-api-library) to integrate with Adyen now. Hence I think it would be in the best interest of the community to deprecate this library in favor of the official one and add a note pointing to the official lib. If you think the official library is missing any features, let us know and we will be happy to consider adding those from this lib. Could you please take a look and consider it?

**Comment by wvanbergen** [comment]
Done!
